# Generated by Django 5.2.3 on 2025-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='accepted_by',
        ),
    ]
