# Generated by Django 5.2.3 on 2025-07-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
