# Generated by Django 5.2.3 on 2025-07-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='api.task'),
        ),
    ]
