# Generated by Django 5.2.3 on 2025-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_filecategory_sharedfile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ชื่อของเทมเพลต เช่น 'หนังสือสั่งการด่วน'", max_length=255, unique=True)),
                ('subject_template', models.CharField(help_text='เทมเพลตสำหรับหัวข้อ Task (เรื่อง)', max_length=255)),
                ('body_template', models.TextField(help_text='เทมเพลตสำหรับเนื้อหา Task (รายละเอียด)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
