# Generated by Django 5.2.3 on 2025-07-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
