# Generated by Django 5.2.3 on 2025-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team'),
        ('api', '0010_sharedfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='accounts.team'),
        ),
    ]
