# Generated by Django 5.2.3 on 2025-07-04 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task_assigned_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, related_name='accepted_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
