# Generated by Django 5.2.3 on 2025-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
