# Generated by Django 5.2.3 on 2025-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='ลายเซ็น (รูปภาพ)'),
        ),
    ]
