# Generated by Django 5.2.3 on 2026-07-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสศูนย์ต้นทุน (cctr)'),
        ),
    ]
