# Generated by Django 5.2.3 on 2026-02-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2570, help_text='ปีงบประมาณ')),
                ('is_active', models.BooleanField(default=True, help_text='เปิดให้กรอกข้อมูลหรือไม่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(help_text='จังหวัดที่ตั้ง', max_length=100)),
                ('category', models.CharField(choices=[('AIR', 'Air Conditioner'), ('RECTIFIER', 'Rectifier'), ('BATTERY', 'Battery'), ('UPS', 'UPS'), ('OTHER', 'Other')], max_length=20)),
                ('location_type', models.CharField(choices=[('EXCHANGE', 'อาคารชุมสาย (Exchange)'), ('SERVICE_CENTER', 'ศูนย์บริการลูกค้า'), ('OFFICE', 'อาคารสำนักงาน'), ('BASE_STATION', 'สถานีฐาน (Base Station)'), ('OTHER', 'อื่นๆ')], max_length=50)),
                ('location_name', models.CharField(help_text='ชื่อสถานที่ เช่น ชุมสายบ้านไผ่', max_length=200)),
                ('asset_number', models.CharField(blank=True, help_text='เลขสินทรัพย์ (ถ้ามี)', max_length=100, null=True)),
                ('brand_model', models.CharField(blank=True, help_text='ยี่ห้อ/รุ่น', max_length=200, null=True)),
                ('install_year', models.IntegerField(help_text='ปีที่ติดตั้ง (ค.ศ.) เพื่อคำนวณอายุ')),
                ('customer_impact', models.IntegerField(default=0, help_text='จำนวนลูกค้าที่ได้รับผลกระทบ (ราย)')),
                ('condition', models.CharField(choices=[('GOOD', 'ใช้งานได้ปกติ'), ('FAIR', 'พอใช้ (เริ่มเสื่อมสภาพ)'), ('POOR', 'ควรเปลี่ยน (เสีย/เสื่อมสภาพมาก)'), ('DAMAGED', 'ชำรุด (ใช้งานไม่ได้)')], default='FAIR', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='เหตุผลความจำเป็นในการขอทดแทน')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='assets/evidence/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='assets/evidence/')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('SUBMITTED', 'ส่งข้อมูลแล้ว'), ('APPROVED', 'ส่วนกลางตรวจสอบแล้ว'), ('REJECTED', 'ตีกลับแก้ไข')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.surveycampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
