# Generated by Django 5.2.3 on 2026-02-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_signature'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='หน่วยงานเจ้าของสินทรัพย์ (ดึงอัตโนมัติจาก User)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_assets', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='province',
            field=models.CharField(blank=True, help_text='ชื่อจังหวัด/ส่วนงาน (Snapshot ณ วันที่บันทึก)', max_length=100),
        ),
    ]
