# Generated by Django 5.2.3 on 2026-02-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetrequest_department_alter_assetrequest_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='air_btu',
            field=models.CharField(blank=True, choices=[('9000', '9,000 BTU'), ('12000', '12,000 BTU'), ('18000', '18,000 BTU'), ('24000', '24,000 BTU'), ('30000', '30,000 BTU'), ('36000', '36,000 BTU'), ('40000+', 'มากกว่า 40,000 BTU')], max_length=20, null=True, verbose_name='ขนาด BTU'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='air_type',
            field=models.CharField(blank=True, choices=[('WALL', 'ติดผนัง (Wall Type)'), ('CEILING', 'แขวนใต้ฝ้า (Ceiling Type)'), ('CASSETTE', 'ฝังฝ้า 4 ทิศทาง (Cassette Type)'), ('FLOOR', 'ตั้งพื้น (Floor Type)'), ('OTHER', 'อื่นๆ')], max_length=20, null=True, verbose_name='ประเภทแอร์'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='battery_amp',
            field=models.IntegerField(blank=True, null=True, verbose_name='ขนาดแอมป์ (Ah)'),
        ),
    ]
