# Generated by Django 5.2.3 on 2026-02-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetrequest_air_btu_assetrequest_air_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='rectifier_amp',
            field=models.IntegerField(blank=True, null=True, verbose_name='ขนาด Rectifier (Amp)'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='ups_kva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ขนาด UPS (kVA)'),
        ),
    ]
