# Generated by Django 5.2.3 on 2026-02-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetrequest_rectifier_amp_assetrequest_ups_kva'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'ขอใหม่ (New Request)'), ('REPLACE', 'ทดแทนของเดิม (Replacement)')], default='REPLACE', max_length=10, verbose_name='ประเภทคำขอ'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขสินทรัพย์'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='brand_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ยี่ห้อ/รุ่น'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='customer_impact',
            field=models.IntegerField(default=0, verbose_name='ผลกระทบลูกค้า'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='install_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ปีที่ติดตั้ง'),
        ),
    ]
