# Generated by Django 5.2.3 on 2026-02-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='อายุการใช้งาน'),
        ),
    ]
