# Generated by Django 5.2.3 on 2026-02-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetrequest_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='air_type',
            field=models.CharField(blank=True, choices=[('WALL_FIXED', 'ติดผนัง (Fixed Speed)'), ('WALL_INVERTER', 'ติดผนัง (Inverter)'), ('CEILING_FIXED', 'ตั้งพื้น/แขวน (Fixed Speed)'), ('CEILING_INVERTER', 'ตั้งพื้น/แขวน (Inverter)'), ('CABINET', 'ตู้ตั้งพื้น (Cabinet)'), ('OTHER', 'อื่นๆ'), ('WALL', 'ติดผนัง (Old)'), ('CEILING', 'แขวน (Old)'), ('CASSETTE', 'ฝังฝ้า (Old)'), ('FLOOR', 'ตั้งพื้น (Old)')], max_length=50, null=True, verbose_name='ชนิดแอร์'),
        ),
    ]
