# Generated by Django 5.2.3 on 2026-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetrequest_air_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='air_btu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ขนาด (BTU)'),
        ),
    ]
