# Generated by Django 5.2.3 on 2026-07-23 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_cost_center'),
        ('assets', '0008_alter_assetrequest_air_btu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(default='2026', max_length=4, verbose_name='ปีงบประมาณ')),
                ('asset_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='คลาส')),
                ('asset_number', models.CharField(db_index=True, max_length=100, verbose_name='รหัสสินทรัพย์')),
                ('description', models.CharField(max_length=500, verbose_name='คำอธิบายของสินทรัพย์')),
                ('cap_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cap.date')),
                ('cost_center', models.CharField(db_index=True, max_length=50, verbose_name='ศ.ต้นทุน')),
                ('fund_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='ศ.เงินทุน')),
                ('apc_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ราคาทุน APC')),
                ('book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='มูลค่าตามบัญชี')),
                ('current_status', models.CharField(choices=[('NORMAL', 'ใช้งานได้ปกติ'), ('BROKEN', 'ชำรุด/รอซ่อม'), ('LOST', 'สูญหาย'), ('TRANSFER', 'โอนย้าย'), ('NOT_FOUND', 'หาไม่พบ/ไม่ทราบสถานะ')], default='NORMAL', max_length=20, verbose_name='สถานะการสำรวจ')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='หมายเหตุจากพื้นที่')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_equipments', to='accounts.department')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cost_center', 'asset_number'],
                'unique_together': {('fiscal_year', 'asset_number')},
            },
        ),
    ]
