# Generated by Django 5.2.3 on 2026-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_annualequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualequipment',
            name='act_typ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ActTyp'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='center_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสศูนย์'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='evg_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EVG.3'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ที่ตั้ง'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='old_asset',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ท/ส เดิม'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ปริมาณ'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='rsp_cctr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rsp.CCtr'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='s_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SNo.'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='sub_dept',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ปภ.ย่อยสท.'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='annualequipment',
            name='asset_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='สินทรัพย์'),
        ),
    ]
