# Generated by Django 5.2.3 on 2026-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_annualequipment_act_typ_annualequipment_center_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualequipment',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='equipment_docs/', verbose_name='เอกสารแนบ PDF'),
        ),
        migrations.AddField(
            model_name='annualequipment',
            name='image_current',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='รูปภาพปัจจุบัน'),
        ),
    ]
