# Generated by Django 5.2.3 on 2026-08-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_annualequipment_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualequipment',
            name='responsible_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หน่วยงาน/ส่วนที่รับผิดชอบ'),
        ),
    ]
