# Generated by Django 5.2.3 on 2025-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_stepattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkflow',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='วงเงินงบประมาณ'),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='pr_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่ PR'),
        ),
    ]
