# Generated by Django 5.2.3 on 2025-08-20 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_projectworkflow_budget_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectworkflow",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="stepstatus",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
