# Generated by Django 5.2.3 on 2025-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_alter_projectworkflow_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectworkflow",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
