# Generated by Django 5.2.3 on 2025-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_projectworkflow_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstatus',
            name='actual_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ปิดงานจริง'),
        ),
    ]
