# Generated by Django 5.2.3 on 2025-10-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_stepstatus_actual_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkflow',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่โปรเจกต์เสร็จสิ้น'),
        ),
    ]
