# Generated by Django 5.2.3 on 2025-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_projectworkflow_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepstatus',
            name='duration_override',
            field=models.IntegerField(blank=True, null=True, verbose_name='ระยะเวลาที่กำหนดเอง (วัน)'),
        ),
    ]
