# Generated by Django 5.2.3 on 2025-11-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_stepstatus_duration_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Category',
                'verbose_name_plural': 'Workflow Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='workflows.workflowcategory', verbose_name='Workflow Category'),
        ),
    ]
