# Generated by Django 5.2.3 on 2026-08-27 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_workflowcategory_projectworkflow_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkflow',
            name='handlers',
            field=models.ManyToManyField(blank=True, related_name='handled_workflows', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบงาน'),
        ),
    ]
