# Generated by Django 5.2.3 on 2025-09-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('LINE', 'Line Notification'), ('TELEGRAM', 'Telegram Notification')], default='INFO', max_length=20),
        ),
    ]
