# Generated by Django 5.2.3 on 2025-07-22 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_tasktemplate'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(help_text='ลำดับของขั้นตอน เช่น 1, 2, 3...')),
                ('responsible_group', models.ForeignKey(blank=True, help_text='กลุ่มผู้ใช้ที่มีสิทธิ์อนุมัติขั้นตอนนี้', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procurement.workflowtemplate')),
            ],
            options={
                'ordering': ['workflow_template', 'order'],
                'unique_together': {('workflow_template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='procurement.procurementrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.step')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.step'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.workflowtemplate'),
        ),
    ]
