# Generated by Django 5.2.3 on 2025-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procurementattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
