# Generated by Django 5.2.3 on 2025-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementattachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='กรอบเวลาสำหรับขั้นตอนนี้ (วัน)'),
        ),
    ]
