# Generated by Django 5.2.3 on 2025-08-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_step_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Procurement Category',
                'verbose_name_plural': 'Procurement Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='procurement.procurementcategory'),
        ),
    ]
