# Generated by Django 5.2.3 on 2025-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('procurement', '0005_procurementcategory_procurementrequest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='responsible_group',
        ),
        migrations.AddField(
            model_name='step',
            name='responsible_groups',
            field=models.ManyToManyField(blank=True, help_text='กลุ่มผู้ใช้ที่มีสิทธิ์อนุมัติขั้นตอนนี้', to='auth.group'),
        ),
    ]
