# Generated by Django 5.2.3 on 2025-08-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_step_responsible_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
