# Generated by Django 5.2.3 on 2025-08-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_procurementrequest_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('SENT_BACK', 'Sent Back')], default='APPROVED', max_length=10),
        ),
    ]
