# Generated by Django 5.2.3 on 2025-09-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_requesthistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_signature_required',
            field=models.BooleanField(default=False, help_text='ขั้นตอนนี้บังคับให้ต้องมีการลงนามในเอกสาร PDF หรือไม่'),
        ),
    ]
