# Generated by Django 5.2.3 on 2025-09-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_step_is_signature_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่หนังสือ'),
        ),
    ]
