# Generated by Django 5.2.3 on 2025-09-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_procurementrequest_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='requires_document_number',
            field=models.BooleanField(default=False, help_text='ติ๊กเลือกหากขั้นตอนนี้จำเป็นต้องมีการกรอกเลขที่หนังสือ', verbose_name='บังคับใส่เลขที่หนังสือ'),
        ),
    ]
