# Generated by Django 5.2.3 on 2025-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_step_requires_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่หนังสือ'),
        ),
    ]
