# Generated by Django 5.2.3 on 2025-10-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_requesthistory_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='requires_attachment',
            field=models.BooleanField(default=False, help_text='ติ๊กเลือกหากขั้นตอนนี้บังคับให้ต้องแนบไฟล์ประกอบอย่างน้อย 1 ไฟล์', verbose_name='บังคับแนบไฟล์'),
        ),
    ]
