# Generated by Django 5.2.3 on 2025-11-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_step_requires_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='template_type',
            field=models.CharField(choices=[('PROCUREMENT', 'งานจัดซื้อจัดจ้าง'), ('WORKFLOW', 'Workflow ทั่วไป')], default='PROCUREMENT', max_length=20, verbose_name='ประเภทแม่แบบ'),
        ),
    ]
