# Generated by Django 5.2.3 on 2025-11-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_workflowtemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='template_type',
            field=models.CharField(choices=[('PROCUREMENT', 'Workflow ทั่วไป'), ('WORKFLOW', 'งานจัดซื้อจัดจ้าง')], default='PROCUREMENT', max_length=20, verbose_name='ประเภทแม่แบบ'),
        ),
    ]
