# Generated by Django 5.2.3 on 2025-11-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_alter_workflowtemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='should_generate_pdf',
            field=models.BooleanField(default=False, help_text='หากเลือก ระบบจะสร้าง PDF บันทึกข้อความอัตโนมัติและแนบไฟล์ให้เมื่ออนุมัติผ่านขั้นตอนนี้', verbose_name='สร้างใบปะหน้าอัตโนมัติ'),
        ),
    ]
