# Generated by Django 5.2.3 on 2025-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_step_should_generate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='requesting_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หน่วยงานที่ขอ'),
        ),
    ]
