# Generated by Django 5.2.3 on 2026-01-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_procurementrequest_requesting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='งบประมาณ'),
        ),
    ]
