# Generated by Django 5.2.3 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_procurementrequest_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementattachment',
            name='file',
            field=models.FileField(upload_to='protected/procurement_attachments/'),
        ),
    ]
