# Generated by Django 5.2.3 on 2026-09-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_alter_procurementattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
