# Generated by Django 5.2.3 on 2026-09-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_alter_procurementrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='ข้อความสรุปสาระสำคัญของโครงการที่ประมวลผลโดย AI', null=True, verbose_name='สรุปเอกสารโดย AI'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='allow_ai_summary',
            field=models.BooleanField(default=False, help_text='หากเลือก ผู้ใช้งานจะสามารถกดปุ่มสรุปเอกสารด้วย AI ในขั้นตอนนี้ได้', verbose_name='อนุญาตให้ใช้ AI สรุปเอกสาร'),
        ),
    ]
